// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwr54k7mSgymLhLX_j1d5DG24meG6HS0',
    appId: '1:503343630355:web:3aa1d95643d34dcbad57e6',
    messagingSenderId: '503343630355',
    projectId: 'fir-81dba',
    authDomain: 'fir-81dba.firebaseapp.com',
    storageBucket: 'fir-81dba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqd9RYU2Mqy6DksEtZ18g2WvRfWc5vrP4',
    appId: '1:503343630355:android:3eae21c1ca52f347ad57e6',
    messagingSenderId: '503343630355',
    projectId: 'fir-81dba',
    storageBucket: 'fir-81dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64okGoAzXg8bUbzoK-idqU3bRFP4P05g',
    appId: '1:503343630355:ios:52e13890311e17dead57e6',
    messagingSenderId: '503343630355',
    projectId: 'fir-81dba',
    storageBucket: 'fir-81dba.appspot.com',
    iosClientId: '503343630355-075rpa4nvn8kn8jiimhth35not07m3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64okGoAzXg8bUbzoK-idqU3bRFP4P05g',
    appId: '1:503343630355:ios:52e13890311e17dead57e6',
    messagingSenderId: '503343630355',
    projectId: 'fir-81dba',
    storageBucket: 'fir-81dba.appspot.com',
    iosClientId: '503343630355-075rpa4nvn8kn8jiimhth35not07m3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwr54k7mSgymLhLX_j1d5DG24meG6HS0',
    appId: '1:503343630355:web:8323c460abc82937ad57e6',
    messagingSenderId: '503343630355',
    projectId: 'fir-81dba',
    authDomain: 'fir-81dba.firebaseapp.com',
    storageBucket: 'fir-81dba.appspot.com',
  );
}
